
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then( () => {
      // Inserts seed entries
      return knex('users').insert([
        {
          id: 1,
          name: 'Josephina',
          spotify_id: 30,
          age: 33,
          gender: 'Female',
          description: 'Im pretty cool',
          latitude: 38.123435,
          longitude: -123.343423,
          photo: 'http://placekitten.com/200/300',
          age_range: '20-30',
          radius: 30,
          desired_gender: 'female',
          match_score: 56,
          top_tracks: {
            "The Beatles": 'Hello',
            "Gregory Allen": 'Stable Song',
            "fish": 'some weird fish song',
            "Kanye West": 'Wolves',
            "The lumineers":'Sick in The Head',
            "The Head and the Heart":'Another Story',
            "Simon & Garfunkel": `Kathy's Song`,
            "The Wood Brothers": 'Postcards From Hell',
            "The Chainsmokers": 'Roses',
            "Tallest Man on Earth":'Love is All'
          },
          top_artists: {
            "The Beatles": 'The Beatles',
            "Gregory Allen": 'Stable Song',
            "fish": 'fish',
            "Kanye West": 'Kanye West',
            "The Lumineers":'The Lumineers',
            "The Head and the Heart":'The Head and the Heart',
            "Simon & Garfunkel": `Simon & Garfunkel`,
            "The Wood Brothers": 'The Wood Brothers',
            "The Chainsmokers": 'The Chainsmokers',
            "Tallest Man on Earth":'Tallest Man on Earth'
          },
          is_initialized: true
        },
        {
          id: 2,
          name: 'Sophia',
          spotify_id: 98,
          age: 24,
          gender: 'Female',
          description: 'Im pretty cool',
          latitude: 38.123435,
          longitude: -123.343423,
          photo: 'https://i.pinimg.com/474x/19/05/9a/19059a24d4c28b6a0f9bdbe7dfd6dcd4.jpg',
          age_range: '20-30',
          radius: 30,
          desired_gender: 'male',
          match_score: 56,
          top_tracks: {
            "Jill Andrews": `I'm so in Love with You`,
            "Gregory Allen": `Oh City Lights`,
            "The Avett Brothers": 'Murder in the City',
            "Mandolin Orange": 'Runnin Red',
            "Simon & Garfunkel":'Song for the Asking',
            "The Head and the Heart":'Another Story',
            "Simon & Garfunkel": `Kathy's Song`,
            "The Wood Brothers": 'Postcards From Hell',
            "The Chainsmokers": 'Roses',
            "Jill Andrews":'A Way to You Again'
          },
          top_artists: {
            "Jill Andrews": `Jill Andrews`,
            "Gregory Allen": `Gregory Allen`,
            "The Avett Brothers": 'The Avett Brothers',
            "Mandolin Orange": 'Mandolin Orange',
            "Simon & Garfunkel":'Simon & Garfunkel',
            "The Head and the Heart":'The Head and the Heart',
            "Simon & Garfunkel": `Simon & Garfunkel`,
            "The Wood Brothers": 'The Wood Brothers',
            "The Chainsmokers": 'The Chainsmokers',
            "Jill Andrews":'Jill Andrews'
          },
        },
        {
          id: 3,
          name: 'Emma',
          spotify_id: 38,
          age: 29,
          gender: 'Female',
          description: 'I never know what to say on these things',
          latitude: 38.123435,
          longitude: -123.343423,
          photo: 'https://pbs.twimg.com/profile_images/848009415206858752/cDMhhlfF_400x400.jpg',
          age_range: '20-30',
          radius: 30,
          desired_gender: 'male',
          match_score: 56,
          top_tracks: {
            "Jill Andrews": `I'm so in Love with You`,
            "Gregory Allen": `Oh City Lights`,
            "The Avett Brothers": 'Murder in the City',
            "Mandolin Orange": 'Runnin Red',
            "Simon & Garfunkel":'Song for the Asking',
            "The Head and the Heart":'Another Story',
            "Simon & Garfunkel": `Kathy's Song`,
            "The Wood Brothers": 'Postcards From Hell',
            "The Chainsmokers": 'Roses',
            "Jill Andrews":'A Way to You Again'
          },
          top_artists: {
            "Jill Andrews": `Jill Andrews`,
            "Gregory Allen": `Gregory Allen`,
            "The Avett Brothers": 'The Avett Brothers',
            "Mandolin Orange": 'Mandolin Orange',
            "Simon & Garfunkel":'Simon & Garfunkel',
            "The Head and the Heart":'The Head and the Heart',
            "Simon & Garfunkel": `Simon & Garfunkel`,
            "The Wood Brothers": 'The Wood Brothers',
            "The Chainsmokers": 'The Chainsmokers',
            "Jill Andrews":'Jill Andrews'
          },
        },
        {
          id: 4,
          name: 'Blake',
          spotify_id: 98,
          age: 30,
          gender: 'female',
          description: 'I hope it runs like a sewing machine',
          latitude: 38.123435,
          longitude: -123.343423,
          photo: 'https://media1.popsugar-assets.com/files/thumbor/AXQvyuxxedjd4ewC2RmftrmjqMw/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2016/05/12/622/n/1922153/d9b67e8d_edit_img_image_41288338_1463060612_a/i/Makeup-Light.jpg',
          age_range: '20-30',
          radius: 30,
          desired_gender: 'male',
          match_score: 56,
          top_tracks: {
            beetles: 'hello',
            fish: 'some weird fish song',
            fake_artist: 'fake_artist greatest hits',

          },
          top_artists: {
            beetles: 'beetles',
            fish: 'fish',
            fake_artist: 'fake_artist',
          },
        },
        {
          id: 6,
          name: 'Andrea',
          spotify_id: 98,
          age: 24,
          gender: 'female',
          description: `I'll get rocking side to side`,
          latitude: 38.123435,
          longitude: -123.343423,
          photo: 'http://images.indianexpress.com/2015/10/arianagrande759.jpg',
          age_range: '20-30',
          radius: 30,
          desired_gender: 'male',
          match_score: 56,
          top_tracks: {
            "Katy Perry": 'Kissed a Girl',
            fish: 'some weird fish song',
            fake_artist: 'fake_artist greatest hits',

          },
          top_artists: {
            beetles: 'beetles',
            fish: 'fish',
            fake_artist: 'fake_artist',
          },
        }
      ]);
    });
};
